# Generated by Django 5.0.7 on 2024-07-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmDjango", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
