# Generated by Django 5.0.7 on 2024-07-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmDjango", "0002_client_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="price",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="applications",
            name="price",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
