# Generated by Django 5.0.7 on 2024-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmDjango", "0003_sales_price_alter_applications_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="status",
            field=models.CharField(blank=True, default="Активна", max_length=10),
        ),
        migrations.AlterField(
            model_name="sales",
            name="isReady",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
